# Generated by Django 5.1.6 on 2025-02-23 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paypal_order_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(default='Guest', max_length=100)),
                ('last_name', models.CharField(default='User', max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('address1', models.CharField(default='Not Provided', max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('zip_code', models.CharField(default='00000', max_length=20)),
                ('phone', models.CharField(default='000-000-0000', max_length=20)),
                ('email', models.EmailField(default='notprovided@example.com', max_length=254)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('check', 'Check Payment'), ('pickup', 'Pickup at Store'), ('paypal', 'PayPal')], default='paypal', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('single', 'Single'), ('bag', 'Bag'), ('box', 'Box')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
