# Generated by Django 5.1.6 on 2025-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refundmedia_uploaded_at_alter_refundrequest_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
