# Generated by Django 5.1.6 on 2025-02-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_refundmedia_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
    ]
