# Generated by Django 5.1.6 on 2025-03-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_is_refundable'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refunded_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
