# Generated by Django 5.1.6 on 2025-03-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_refunded_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='paypal_refund_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='refundmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
