# Generated by Django 5.1.6 on 2025-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_refundrequest_paypal_refund_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
