# Generated by Django 5.1.6 on 2025-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Direct Bank Transfer'), ('check', 'Check Payment'), ('pickup', 'Pay at Store'), ('paypal', 'PayPal')], default='paypal', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
