# Generated by Django 5.1.6 on 2025-04-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('pickup', 'Pickup at Store'), ('delivery', 'Delivery')], default='pickup', max_length=20),
        ),
    ]
