# Generated by Django 5.1.6 on 2025-04-25 23:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_shipping_address1_order_shipping_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='restocking_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Restocking fee percentage', max_digits=5),
        ),
    ]
