# Generated by Django 5.1.6 on 2025-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_refundrequest_restocking_fee_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Preparing', 'Preparing'), ('ReadyForPickup', 'Ready for Pickup'), ('ReadyToShip', 'Ready to Ship'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
