# Generated by Django 5.1.6 on 2025-03-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_product'),
        ('store', '0008_pricerule_apply_to_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariation'),
        ),
    ]
