# Generated by Django 5.1.6 on 2025-02-26 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
