# Generated by Django 5.1.6 on 2025-03-18 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_online_customuser_member_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pos',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to the POS system.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pos_pin',
            field=models.CharField(blank=True, help_text='Enter a 4-6 digit PIN if POS access is enabled.', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='PIN must be 4 to 6 digits', regex='^[0-9]{4,6}$')]),
        ),
    ]
