# Generated by Django 5.1.6 on 2025-02-23 21:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_history', models.JSONField(blank=True, default=list)),
                ('system_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('upc', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('custom_sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('publish_to_ecommerce', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('rating', models.FloatField(default=0)),
                ('trending', models.BooleanField(default=False)),
                ('best_selling', models.BooleanField(default=False)),
                ('most_popular', models.BooleanField(default=False)),
                ('just_arrived', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price_single', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_single', models.IntegerField(default=0)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bag_size', models.IntegerField(default=1)),
                ('price_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_bag', models.IntegerField(default=0)),
                ('box_size', models.IntegerField(default=1)),
                ('price_box', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock_box', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variations/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('products', models.ManyToManyField(blank=True, related_name='price_lists', to='store.product')),
                ('product_variations', models.ManyToManyField(blank=True, related_name='price_lists', to='store.productvariation')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.subcategory'),
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('customer_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum')], max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 20 for 20%)', max_digits=5)),
                ('apply_to_categories', models.ManyToManyField(blank=True, help_text='Apply to these categories', to='store.category')),
                ('apply_to_price_list', models.ForeignKey(blank=True, help_text='Apply to a specific price list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pricelist')),
                ('exclude_products', models.ManyToManyField(blank=True, related_name='excluded_from_discount', to='store.product')),
                ('apply_to_variations', models.ManyToManyField(blank=True, help_text='Apply to specific product variations', related_name='price_rules', to='store.productvariation')),
                ('exclude_variations', models.ManyToManyField(blank=True, related_name='excluded_from_discount', to='store.productvariation')),
                ('apply_to_subcategories', models.ManyToManyField(blank=True, help_text='Apply to these subcategories', to='store.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.vendor'),
        ),
    ]
