# Generated by Django 5.1.6 on 2025-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='Mark if this product can be refunded.'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_refundable',
            field=models.BooleanField(default=True, help_text='Mark if this product can be refunded.'),
        ),
    ]
