# Generated by Django 5.1.6 on 2025-03-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_refundable_productvariation_is_refundable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_bag',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_box',
        ),
    ]
