# Generated by Django 5.1.6 on 2025-03-11 05:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the box type (e.g., Small, Medium, Large).', max_length=50, unique=True)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity for this box in lbs.', max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, help_text='Internal length of the box in inches.', max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, help_text='Internal width of the box in inches.', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Internal height of the box in inches.', max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.0'), help_text='Default height in inches', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.0'), help_text='Default length in inches', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Default weight per unit (lbs)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.0'), help_text='Default width in inches', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='bag_height',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Bag height in inches for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='bag_length',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Bag length in inches for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='bag_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Weight per bag (lbs) for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='bag_width',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Bag width in inches for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='box_height',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Box height in inches for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='box_length',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Box length in inches for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='box_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Weight per box (lbs) for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='box_width',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Box width in inches for this variation', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.0'), help_text='Height in inches', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='length',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.0'), help_text='Length in inches', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Weight per unit (lbs)', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.0'), help_text='Width in inches', max_digits=6),
        ),
    ]
