# Generated by Django 5.1.6 on 2025-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_boxsize_product_height_product_length_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='custom_sku',
            field=models.CharField(blank=True, help_text='Custom SKU', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='ean',
            field=models.CharField(blank=True, help_text='EAN code', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='manufacturer_sku',
            field=models.CharField(blank=True, help_text='Manufacturer SKU', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='upc',
            field=models.CharField(blank=True, help_text='UPC code', max_length=12, null=True),
        ),
    ]
