# Generated by Django 5.1.6 on 2025-03-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_pricerule_apply_to_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
