# Generated by Django 5.1.6 on 2025-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productvariation_variation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, unique=True),
        ),
    ]
