# Generated by Django 5.1.6 on 2025-03-20 21:55

from django.db import migrations
import uuid

def generate_variation_id():
    return "VAR" + uuid.uuid4().hex[:10].upper()

def update_variation_ids(apps, schema_editor):
    # Get the historical ProductVariation model
    ProductVariation = apps.get_model('store', 'ProductVariation')
    # Find variations with an empty string or null in variation_id
    variations = ProductVariation.objects.filter(variation_id__in=["", None])
    for variation in variations:
        variation.variation_id = generate_variation_id()
        variation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productvariation_variation_id'),
    ]

    operations = [
        migrations.RunPython(update_variation_ids),
    ]
