# Generated by Django 5.1.6 on 2025-03-20 22:00

from django.db import migrations, models
import uuid

def generate_variation_id():
    return "VAR" + uuid.uuid4().hex[:10].upper()

def set_variation_ids(apps, schema_editor):
    ProductVariation = apps.get_model('store', 'ProductVariation')
    # Filter variations with empty or NULL variation_id
    qs = ProductVariation.objects.filter(models.Q(variation_id="") | models.Q(variation_id__isnull=True))
    for pv in qs:
        new_id = generate_variation_id()
        pv.variation_id = new_id
        pv.save()
        # Optionally, you can print to the console for debugging:
        print(f"Updated ProductVariation (id: {pv.id}) with variation_id: {new_id}")

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20250320_1755'),
    ]

    operations = [
        migrations.RunPython(set_variation_ids, reverse_code=migrations.RunPython.noop),
    ]
