# Generated by Django 5.1.6 on 2025-03-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20250320_1758'),
        ('store', '0014_auto_20250320_1800'),
    ]

    operations = [
    ]
