# Generated by Django 5.1.6 on 2025-03-20 22:07

import uuid
from django.db import migrations

def generate_variation_id():
    return "VAR" + uuid.uuid4().hex[:10].upper()

def fill_variation_ids(apps, schema_editor):
    ProductVariation = apps.get_model('store', 'ProductVariation')
    # Filter variations that have a blank or null variation_id
    variations = ProductVariation.objects.filter(variation_id__in=["", None])
    for variation in variations:
        new_id = generate_variation_id()
        variation.variation_id = new_id
        variation.save(update_fields=["variation_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_merge_0013_auto_20250320_1758_0014_auto_20250320_1800'),
    ]

    operations = [
        migrations.RunPython(fill_variation_ids, reverse_code=migrations.RunPython.noop),
    ]
