# Generated by Django 5.1.6 on 2025-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, default='No additional information available.', help_text="Additional product details (defaults to 'No additional information available.')", null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='default_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default cost for a single item variation', max_digits=10, null=True),
        ),
    ]
