# Generated by Django 5.1.6 on 2025-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text="Quantity above which products are shown as 'In Stock'"),
        ),
    ]
